const eraQuizBanks = {
  past: [
    {
      question: "Which institute built India's first indigenous computer TIFRAC?",
      options: ["IIT Bombay", "TIFR", "IISc", "BARC"],
      answer: 1,
      fact: "TIFR engineers completed TIFRAC in 1960 for atomic research.",
    },
    {
      question: "In which year was ISRO formed?",
      options: ["1958", "1969", "1975", "1984"],
      answer: 1,
      fact: "ISRO was established in 1969 under Vikram Sarabhai's guidance.",
    },
    {
      question: "C-DOT exchanges were famous for enabling what?",
      options: ["Weather satellites", "Rural telecom", "Rail signaling", "Cinema audio"],
      answer: 1,
      fact: "C-DOT rugged digital exchanges powered rural telephony rollouts.",
    },
    {
      question: "Which city hosts the Electronics Corporation of India (ECIL)?",
      options: ["Mumbai", "Hyderabad", "Kolkata", "Pune"],
      answer: 1,
      fact: "ECIL's Hyderabad campus produced control systems and defense electronics.",
    },
    {
      question: "What did NICNET connect in the 1980s?",
      options: ["Village schools", "District data centers", "TV broadcasters", "Ports"],
      answer: 1,
      fact: "NICNET linked district informatics offices for governance data.",
    },
    {
      question: "PARAM 8000 was launched by C-DAC in which year?",
      options: ["1985", "1991", "1998", "2003"],
      answer: 1,
      fact: "C-DAC's PARAM 8000 debuted in 1991, bypassing supercomputer embargoes.",
    },
    {
      question: "The first Software Technology Park (STPI) pilots emerged in?",
      options: ["Bhubaneswar", "Chennai", "Lucknow", "Indore"],
      answer: 0,
      fact: "Bhubaneswar's STPI (1989) offered satellite links for software exports.",
    },
    {
      question: "Which body preceded ISRO for space research?",
      options: [
        "INCOSPAR",
        "DRDO",
        "Atomic Energy Commission",
        "BARC",
      ],
      answer: 0,
      fact: "INCOSPAR (1962) laid the groundwork before ISRO's formation.",
    },
    {
      question: "India's first satellite Aryabhata launched in?",
      options: ["1971", "1975", "1979", "1984"],
      answer: 1,
      fact: "Aryabhata flew in 1975 aboard Russia's Kosmos-3M rocket.",
    },
    {
      question: "Which lab pioneered speech synthesis in Indian languages?",
      options: ["IIT Madras", "IIT Kanpur", "TIFR", "ISI Kolkata"],
      answer: 1,
      fact: "IIT Kanpur's labs worked on early Indian language computing.",
    },
    {
      question: "Doordarshan's first colour telecast covered which event?",
      options: [
        "Hockey World Cup",
        "Independence Day 1982",
        "Asian Games 1982",
        "Republic Day 1983",
      ],
      answer: 2,
      fact: "The 1982 Asian Games pushed India into colour TV era.",
    },
    {
      question: "Which mission created indigenous launch vehicles in 1970s?",
      options: ["SLV-3", "PSLV", "GSLV", "ASLV"],
      answer: 0,
      fact: "APJ Abdul Kalam led the SLV-3 program for early launches.",
    },
    {
      question: "Who spearheaded India's early atomic energy program?",
      options: ["Satish Dhawan", "Homi Bhabha", "M.S. Swaminathan", "Verghese Kurien"],
      answer: 1,
      fact: "Dr. Homi Bhabha founded TIFR and steered atomic energy research.",
    },
    {
      question: "Which organization set up the ERNET academic network?",
      options: ["DRDO", "DoT", "Education Ministry", "STPI"],
      answer: 1,
      fact: "Department of Telecommunications supported ERNET for universities.",
    },
    {
      question: "What did the Indian Institutes of Technology initially emphasize?",
      options: ["Retail management", "Heavy engineering", "Space tourism", "E-commerce"],
      answer: 1,
      fact: "IITs were built to power heavy engineering and research capacity.",
    },
  ],
  present: [
    {
      question: "Which rail unbundles e-commerce in India?",
      options: ["ONDC", "FASTag", "BHIM", "GSTN"],
      answer: 0,
      fact: "ONDC lets sellers and buyers transact across interoperable apps.",
    },
    {
      question: "UPI crossed 10B monthly transactions in which year?",
      options: ["2021", "2022", "2023", "2024"],
      answer: 2,
      fact: "UPI hit the 10B mark in August 2023.",
    },
    {
      question: "Which startup launched the Agnibaan SOrTeD rocket?",
      options: ["Skyroot", "Agnikul", "Bellatrix", "Pixxel"],
      answer: 1,
      fact: "Agnikul Cosmos fired Agnibaan with a 3D-printed engine.",
    },
    {
      question: "Account Aggregator frameworks help mainly with?",
      options: ["Gaming", "Credit underwriting", "Logistics", "Edtech"],
      answer: 1,
      fact: "AA frameworks share financial data for better lending decisions.",
    },
    {
      question: "Which telemedicine service crossed 100M consultations?",
      options: ["Aarogya Setu", "eSanjeevani", "Practo", "DocsApp"],
      answer: 1,
      fact: "eSanjeevani enables OPD tele-consults across states.",
    },
    {
      question: "CoWIN primarily managed what?",
      options: ["GST returns", "Vaccine logistics", "EV charging", "Passport renewals"],
      answer: 1,
      fact: "CoWIN coordinated COVID-19 vaccination appointments nationwide.",
    },
    {
      question: "Which city hosts the highest unicorn concentration?",
      options: ["Delhi NCR", "Mumbai", "Bengaluru", "Hyderabad"],
      answer: 2,
      fact: "Bengaluru leads India's unicorn tally.",
    },
    {
      question: "What does DPDP Act focus on?",
      options: [
        "Personal data protection",
        "Public debt",
        "Postal deregulation",
        "Petroleum pricing",
      ],
      answer: 0,
      fact: "The DPDP Act governs consent-based personal data usage.",
    },
    {
      question: "Which firm became India's first listed SaaS unicorn?",
      options: ["Freshworks", "Zoho", "Chargebee", "Postman"],
      answer: 0,
      fact: "Freshworks listed on NASDAQ in 2021.",
    },
    {
      question: "Which mobility initiative pushes EV battery swapping?",
      options: ["FAME", "Sagarmala", "PM Gati Shakti", "UDAN"],
      answer: 0,
      fact: "FAME incentives accelerate EV adoption and swapping infra.",
    },
    {
      question: "Which mission backs semiconductor fabs in India?",
      options: [
        "Digital India",
        "Semicon India",
        "Startup India",
        "PM-KISAN",
      ],
      answer: 1,
      fact: "Semicon India program funds fabs, ATMP, and design-linked incentives.",
    },
    {
      question: "ONDC pilots first launched in which sectors?",
      options: ["Travel", "Retail & food", "Education", "Gaming"],
      answer: 1,
      fact: "ONDC started with groceries and food delivery pilots.",
    },
    {
      question: "Which startup sent hyperspectral satellites to orbit?",
      options: ["Pixxel", "Bellatrix", "Dhruva", "Astrome"],
      answer: 0,
      fact: "Pixxel operates hyperspectral imaging constellations.",
    },
    {
      question: "The Open Credit Enablement Network (OCEN) targets?",
      options: ["Consumer gaming", "Embedded finance", "Television", "Agro seeds"],
      answer: 1,
      fact: "OCEN provides open APIs for embedded lending to MSMEs.",
    },
    {
      question: "Which city hosted India's 2023 G20 digital hubs?",
      options: ["Ahmedabad", "New Delhi", "Lucknow", "Panaji"],
      answer: 1,
      fact: "New Delhi's Bharat Mandapam showcased DPI to G20 delegates.",
    },
  ],
  future: [
    {
      question: "Gaganyaan aims to send astronauts to?",
      options: ["Moon orbit", "Low Earth Orbit", "Mars orbit", "Venus flyby"],
      answer: 1,
      fact: "Gaganyaan's crew module targets Low Earth Orbit missions.",
    },
    {
      question: "Which mission explores the Sun?",
      options: ["Aditya-L1", "Chandrayaan", "Mangalyaan", "Shukrayaan"],
      answer: 0,
      fact: "Aditya-L1 studies solar storms from Lagrange point L1.",
    },
    {
      question: "National Quantum Mission earmarks roughly how much funding?",
      options: ["₹600 Cr", "₹6,000 Cr", "₹60,000 Cr", "₹6 lakh Cr"],
      answer: 1,
      fact: "₹6,000 Cr powers India's quantum computing roadmap.",
    },
    {
      question: "Which initiative champions green hydrogen corridors?",
      options: ["National Hydrogen Mission", "Sagarmala", "PM-KUSUM", "Digital India"],
      answer: 0,
      fact: "The National Hydrogen Mission promotes electrolyzer clusters.",
    },
    {
      question: "6G testbeds are being built across how many labs (approx.)?",
      options: ["10", "25", "50", "75"],
      answer: 3,
      fact: "Over 75 labs contribute to India's 6G testbeds.",
    },
    {
      question: "Shukrayaan mission plans to study which planet?",
      options: ["Mars", "Venus", "Jupiter", "Mercury"],
      answer: 1,
      fact: "Shukrayaan will orbit Venus to study its atmosphere.",
    },
    {
      question: "Which concept imagines a secure digital twin for cities?",
      options: ["National Digital Twin", "City OS", "Urban Stack", "INDUS GRID"],
      answer: 2,
      fact: "Urban Stack proposals combine geospatial, civic, and IoT data.",
    },
    {
      question: "Reusable launch vehicles under development aim to cut costs by?",
      options: ["10%", "25%", "40%", "60%+"],
      answer: 3,
      fact: "ISRO envisions 60%+ cost reduction via reusable boosters.",
    },
    {
      question: "Which mission envisions deep-sea submersibles?",
      options: ["Samudrayaan", "Sagarmala", "BharatNet 2.0", "UDAN"],
      answer: 0,
      fact: "Samudrayaan will send crewed submersibles 6,000m underwater.",
    },
    {
      question: "Future semiconductor nodes India targets first?",
      options: ["5nm", "3nm", "28nm & specialty", "90nm"],
      answer: 2,
      fact: "Initial fabs focus on 28nm, analog, and compound semiconductors.",
    },
    {
      question: "Blue economy drones aim to monitor?",
      options: ["Stock markets", "Coastal fisheries", "Mountain snow", "Traffic lights"],
      answer: 1,
      fact: "Autonomous drones will track coasts and aquaculture health.",
    },
    {
      question: "Quantum-safe communication pilots will protect?",
      options: ["Arcades", "Financial grids", "Gardens", "Theme parks"],
      answer: 1,
      fact: "Quantum key distribution will secure financial and defense links.",
    },
    {
      question: "Which program nurtures AI for 22 Indian languages?",
      options: ["Bhashini", "Diwas", "NavIC", "GatiShakti"],
      answer: 0,
      fact: "Bhashini builds multilingual datasets and speech stacks.",
    },
    {
      question: "Future EV mega factories plan to integrate?",
      options: [
        "Sodium-ion cells",
        "Coal power plants",
        "Manual assembly only",
        "Dial-up modems",
      ],
      answer: 0,
      fact: "Sodium-ion chemistries are slated for localized battery plants.",
    },
    {
      question: "Which mission imagines Indian space stations?",
      options: ["Bharatiya Antariksha Station", "Vande Bharat", "Digital India", "PMJDY"],
      answer: 0,
      fact: "ISRO proposes Bharatiya Antariksha Station after 2035.",
    },
  ],
};
